//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        public int MaHocSinh { get; set; }
        public string TenHocSInh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> MaLop { get; set; }
    
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
